# Generated by Django 3.2.9 on 2021-12-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_app.boardgame')),
            ],
            options={
                'verbose_name_plural': 'avaible games',
            },
        ),
    ]
